package tr.gov.cbrt.hwOwl.model.impl;

import tr.gov.cbrt.hwOwl.model.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMPCdecision <br>
 * @version generated on Wed Dec 07 16:17:27 MSK 2016 by Alperen
 */
public class DefaultMPCdecision extends WrappedIndividualImpl implements MPCdecision {

    public DefaultMPCdecision(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
