package tr.gov.cbrt.hwOwl.model.impl;

import tr.gov.cbrt.hwOwl.model.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultDeputyGovernor <br>
 * @version generated on Wed Dec 07 16:17:27 MSK 2016 by Alperen
 */
public class DefaultDeputyGovernor extends WrappedIndividualImpl implements DeputyGovernor {

    public DefaultDeputyGovernor(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://www.semanticweb.org/tp11501203/owl/ontology#IDinfo
     */
     
    public Collection<? extends Object> getIDinfo() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IDINFO, Object.class);
    }

    public boolean hasIDinfo() {
		return !getIDinfo().isEmpty();
    }

    public void addIDinfo(Object newIDinfo) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IDINFO, newIDinfo);
    }

    public void removeIDinfo(Object oldIDinfo) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_IDINFO, oldIDinfo);
    }


}
