package tr.gov.cbrt.hwOwl.model;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Wed Dec 07 16:17:27 MSK 2016 by Alperen
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/Partner
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARTNER.<p>
     * 
     */
    public static final OWLClass CLASS_PARTNER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/Partner"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Accounting
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACCOUNTING.<p>
     * 
     */
    public static final OWLClass CLASS_ACCOUNTING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Accounting"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#AuditComminity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AUDITCOMMINITY.<p>
     * 
     */
    public static final OWLClass CLASS_AUDITCOMMINITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#AuditComminity"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Banking
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BANKING.<p>
     * 
     */
    public static final OWLClass CLASS_BANKING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Banking"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Banknote
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BANKNOTE.<p>
     * 
     */
    public static final OWLClass CLASS_BANKNOTE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Banknote"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Board
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BOARD.<p>
     * 
     */
    public static final OWLClass CLASS_BOARD = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Board"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Branches
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BRANCHES.<p>
     * 
     */
    public static final OWLClass CLASS_BRANCHES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Branches"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Business
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUSINESS.<p>
     * 
     */
    public static final OWLClass CLASS_BUSINESS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Business"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Comminication
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMMINICATION.<p>
     * 
     */
    public static final OWLClass CLASS_COMMINICATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Comminication"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#ComminityMember
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMMINITYMEMBER.<p>
     * 
     */
    public static final OWLClass CLASS_COMMINITYMEMBER = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#ComminityMember"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Corporation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CORPORATION.<p>
     * 
     */
    public static final OWLClass CLASS_CORPORATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Corporation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Department
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEPARTMENT.<p>
     * 
     */
    public static final OWLClass CLASS_DEPARTMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Department"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#DeputyGovernor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEPUTYGOVERNOR.<p>
     * 
     */
    public static final OWLClass CLASS_DEPUTYGOVERNOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#DeputyGovernor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#ExecutiveComminity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EXECUTIVECOMMINITY.<p>
     * 
     */
    public static final OWLClass CLASS_EXECUTIVECOMMINITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#ExecutiveComminity"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#GeneralAssembly
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GENERALASSEMBLY.<p>
     * 
     */
    public static final OWLClass CLASS_GENERALASSEMBLY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#GeneralAssembly"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Governor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GOVERNOR.<p>
     * 
     */
    public static final OWLClass CLASS_GOVERNOR = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Governor"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#HumanResources
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HUMANRESOURCES.<p>
     * 
     */
    public static final OWLClass CLASS_HUMANRESOURCES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#HumanResources"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#IT
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IT.<p>
     * 
     */
    public static final OWLClass CLASS_IT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#IT"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Intern
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INTERN.<p>
     * 
     */
    public static final OWLClass CLASS_INTERN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Intern"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Legal
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEGAL.<p>
     * 
     */
    public static final OWLClass CLASS_LEGAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Legal"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Logistic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LOGISTIC.<p>
     * 
     */
    public static final OWLClass CLASS_LOGISTIC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Logistic"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#MPC
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MPC.<p>
     * 
     */
    public static final OWLClass CLASS_MPC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#MPC"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#MPCdecision
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MPCDECISION.<p>
     * 
     */
    public static final OWLClass CLASS_MPCDECISION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#MPCdecision"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#NonProfit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NONPROFIT.<p>
     * 
     */
    public static final OWLClass CLASS_NONPROFIT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#NonProfit"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Organization
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ORGANIZATION.<p>
     * 
     */
    public static final OWLClass CLASS_ORGANIZATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Organization"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Partnership
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PARTNERSHIP.<p>
     * 
     */
    public static final OWLClass CLASS_PARTNERSHIP = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Partnership"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#PaymentSystems
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PAYMENTSYSTEMS.<p>
     * 
     */
    public static final OWLClass CLASS_PAYMENTSYSTEMS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#PaymentSystems"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Person
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERSON.<p>
     * 
     */
    public static final OWLClass CLASS_PERSON = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Person"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Private
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRIVATE.<p>
     * 
     */
    public static final OWLClass CLASS_PRIVATE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Private"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Product
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRODUCT.<p>
     * 
     */
    public static final OWLClass CLASS_PRODUCT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Product"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Public
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PUBLIC.<p>
     * 
     */
    public static final OWLClass CLASS_PUBLIC = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Public"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Research
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESEARCH.<p>
     * 
     */
    public static final OWLClass CLASS_RESEARCH = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Research"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Service
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SERVICE.<p>
     * 
     */
    public static final OWLClass CLASS_SERVICE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Service"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Staff
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STAFF.<p>
     * 
     */
    public static final OWLClass CLASS_STAFF = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Staff"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#StatisticalBroadcast
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STATISTICALBROADCAST.<p>
     * 
     */
    public static final OWLClass CLASS_STATISTICALBROADCAST = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#StatisticalBroadcast"));

    /* ***************************************************
     * Class http://www.semanticweb.org/tp11501203/owl/ontology#Statistics
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STATISTICS.<p>
     * 
     */
    public static final OWLClass CLASS_STATISTICS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Statistics"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/tp11501203/owl/ontology#attendsAt
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ATTENDSAT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ATTENDSAT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#attendsAt"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/tp11501203/owl/ontology#broadcasts
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BROADCASTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BROADCASTS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#broadcasts"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/tp11501203/owl/ontology#decides
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DECIDES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DECIDES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#decides"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/tp11501203/owl/ontology#has
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#has"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/tp11501203/owl/ontology#outputs
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OUTPUTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OUTPUTS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#outputs"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/tp11501203/owl/ontology#produces
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRODUCES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRODUCES = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#produces"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/tp11501203/owl/ontology#worksAt
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WORKSAT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WORKSAT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#worksAt"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/tp11501203/owl/ontology#worksIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property WORKSIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_WORKSIN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#worksIn"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL_TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/tp11501203/owl/ontology#BirthDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BIRTHDATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BIRTHDATE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#BirthDate"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/tp11501203/owl/ontology#DogumTarihi
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DOGUMTARIHI.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DOGUMTARIHI = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#DogumTarihi"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/tp11501203/owl/ontology#FirstName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property FIRSTNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_FIRSTNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#FirstName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/tp11501203/owl/ontology#Gender
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property GENDER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_GENDER = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Gender"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/tp11501203/owl/ontology#IDinfo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IDINFO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IDINFO = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#IDinfo"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/tp11501203/owl/ontology#IDno
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property IDNO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_IDNO = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#IDno"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/tp11501203/owl/ontology#LastName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LASTNAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LASTNAME = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#LastName"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/tp11501203/owl/ontology#Title
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property TITLE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_TITLE = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/tp11501203/owl/ontology#Title"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#topDataProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OWL:TOPDATAPROPERTY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OWL_TOPDATAPROPERTY = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#topDataProperty"));


}
